### ISSUE TITLE
No download

### ISSUE THREAD

**Issue by SkippTekk** [xyx0826/Priceall#13]
So, a few of us got interested on trying this. The download button doesn't exist on that website. Care to elaberate on how to grab it? https://gyazo.com/a754d734eee4c65274342d9b7c6effcc

**Comment by xyx0826** [comment]
Thanks for the heads up. AppVeyor no longer store build outputs permanently, and it's been a while since my last commit, so AppVeyor deleted all the artifacts.

I've just published a GitHub release (and made a few bugfixes,) you can find it here: https://github.com/xyx0826/Priceall/releases

Let me know how it goes.

**Comment by xyx0826** [comment]
For the record: I'll publish all future versions, if any, in GitHub releases. If it's been less than a month since my last commit, you can also find the automatic build on AppVeyor. (And of course, you can build it yourself if you have Visual Studio.)

**Comment by SkippTekk** [comment]
Yeh, was too lazy to use Visual Studio, as i don't use it, i use VSCodium. Feel free to close this when you want too.

**Comment by xyx0826** [comment]
With the .NET compiler you can also `dotnet build Priceall.csproj` with no IDE needed. I'll add these to the README.
